import type { Metadata } from "next";
import { Inter_Tight, Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import HeaderTest from "@/components/Header test";
import HeaderSlate from "@/components/HeaderSlate";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

const robotoLight = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto-light",
});

const interTightRegular = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${interTightRegular.variable} relative theme-dark antialiased font-interTight text-white`}
      >
        {/* <Header /> */}
        {/* <HeaderTest /> */}
        <HeaderSlate />
        {children}
      </body>
    </html>
  );
}
